spring.application.name=medilabo-auth-service
server.port=9000

jwt.issuer=medilabo-auth
jwt.ttl-minutes=60

# IMPORTANT: keys folder is at repo root (same level as services)
jwt.private-key-location=file:/Users/madhurijampana/MediLabo/keys/private.pem
logging.level.org.springframework.security=DEBUG
