server.port=9000
spring.application.name=medilabo-auth-service

# JWT
jwt.issuer=medilabo-auth
jwt.ttl-minutes=60

# ? Docker-safe: load from classpath
jwt.private-key-location=classpath:private.pem
jwt.public-key-location=classpath:public.pem
