spring.application.name=medilabo-notes
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/medilabo
spring.security.oauth2.resourceserver.jwt.public-key-location=file:/Users/madhurijampana/MediLabo/keys/public.pem