spring.application.name=medilabo-risk-service
server.port=8083

# Optional (only needed if you validate JWT inside risk-service)
jwt.issuer=medilabo-auth
jwt.public-key-location=file:/Users/madhurijampana/MediLabo/keys/public.pem

# ? These are the keys your properties already use
patient.service.base-url=http://localhost:8081
notes.service.base-url=http://localhost:8082

service.timeout-ms=2000

logging.level.org.springframework.security=DEBUG
