spring.application.name=medilabo-risk-service
server.port=8083

service.timeout-ms=2000

logging.level.org.springframework.security=INFO

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public.pem

patient.service.base-url=${PATIENT_SERVICE_BASE_URL:http://demographics-service:8081}
notes.service.base-url=${NOTES_SERVICE_BASE_URL:http://notes-service:8082}