spring.application.name=medilabo-risk-service
server.port=8083

# risk-service does NOT validate JWT (no JwtDecoder needed)
# it only forwards Authorization header to gateway for patient/notes calls

patient.service.url=http://localhost:8080
notes.service.url=http://localhost:8080

service.timeout-ms=2000

logging.level.org.springframework.security=INFO

spring.security.oauth2.resourceserver.jwt.public-key-location=file:/Users/madhurijampana/MediLabo/keys/public.pem
